# Generated by Django 6.0.3 on 2026-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_supportticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('question', 'Вопрос'), ('Жалоба', 'complant'), ('Предложение', 'suggestion'), ('Техническая проблема', 'technical'), ('other', 'Другое')], default='question', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'низкий'), ('средний', 'medium'), ('high', 'высокий'), ('Срочный', 'urgent')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новые'), ('in_progress', 'В процессе'), ('решено', 'resolved'), ('closed', 'закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
